services:
  qdrant:
    image: qdrant/qdrant # specific version skip :v1.8.0 for latest version
    ports:
      - "6333:6333" # REST API port
      - "6334:6334" # gRPC port
    volumes:
      - "/e/dev docker/qdrant_data:/qdrant/storage"
